import mongoose from 'mongoose';
import { IMain, Main } from '../models/main_schema';
import dotenv from 'dotenv';
import path from 'path';

const envPath = path.resolve(__dirname, '../../.env');

dotenv.config({ path: envPath });

const uri = process.env.MONGO_URI || '';

interface ILaunchInfo {
    launchName: string;
    companyName: string;
    language: string;
    startDate: string;
    endDate: string;
    isActive: boolean;
    id: string;
}

async function connectToDatabase() {
    if (mongoose.connection.readyState === 0) {
        try {
            await mongoose.connect(uri);
            console.log("Connected to MongoDB");
        } catch (err) {
            console.error("MongoDB connection error:", err);
            throw err;
        }
    }
}

function transformResponse(data: any[]): ILaunchInfo[] {
    return data.map(item => ({
        id: item._id,  // <-- Create new id generated by launch counter
        launchName: item.LaunchFormData.launchName,
        companyName: item.LaunchFormData.companyName,
        language: item.LaunchFormData.language,
        isActive: item.LaunchFormData.isActive,
        startDate: item.LaunchFormData.startDate,
        endDate: item.LaunchFormData.endDate,
    }));
}


async function readListLansman(): Promise<ILaunchInfo[]> {
    try {
        await connectToDatabase();
        const posts = await Main.find({}, 'LaunchFormData.launchName LaunchFormData.companyName LaunchFormData.language LaunchFormData.startDate LaunchFormData.endDate LaunchFormData.isActive');
        return transformResponse(posts);
    } catch (err) {
        console.error("Error reading posts:", err);
        throw err;
    } finally {
        mongoose.connection.close();
    }
}

async function readLaunch(id: string): Promise<IMain> {
    try {
        await connectToDatabase();
        const post = await Main.findById(id);
        if (!post) {
            throw new Error("Post not found");
        }
        return post;
    } catch (err) {
        console.error("Error reading post:", err);
        throw err;
    } finally {
        mongoose.connection.close();
    }
}

async function readAllData(): Promise<IMain[]> {
    try {
        await connectToDatabase();
        const mains = await Main.find({});
        return mains;
    } catch (err) {
        console.error("Error reading Mains:", err);
        throw err;
    } finally {
        mongoose.connection.close();
    }
}

export { readListLansman, readLaunch, readAllData };